### ISSUE TITLE
Settings window obscrubed by main window.... and.... I like what you've done with the project!

### ISSUE THREAD

**Issue by PySimpleGUI** [PETEROLO291/Flame-Auto-Clicker#6]
**Describe the Question/Bug/Issue**

Was here to pay you a compliment in general, not report a problem.

**There is so much to like about this project!**
![image](https://user-images.githubusercontent.com/46163555/141306003-6d91d32f-ca6c-43e7-bf63-7714a056f0b5.png)

* You've got screenshots in your readme
* Your app has a custom icon (if you base64 encode it you won't need the file and it'll be portable). Using set_options you can ensure it's used in all windows created in your program
* You've gone the extra mile by extending PySimpleGUI using the Widget member variable to get to settings not yet exposed
* You use this template in your issues
* Plus plenty more I've not listed

While playing with it I noticed that the settings window is hidden behind the main window

Setting keep on top in the settings window creation fixes it.

```python
    pop = sg.Window('Settings', layout, size=(280, 219), element_justification="C", icon="ico.ico", finalize=True, keep_on_top=True)
```

While skimming through the code, I noted that at one point topmost was set using the root variable.  You can do the same thing using the call `window.keep_on_top_set()` so that you'll be more portable.

Themes - there's now a call to add a new theme rather than messing with the dictionary directly.  I clearly need to update the demos and cookbook.

![image](https://user-images.githubusercontent.com/46163555/141306857-df5fd348-24f5-47d9-9e18-3fe2c5f40aee.png)

```python
# Custop dark theme configuration
sg.theme_add_new('CustomDarkTheme', {'BACKGROUND': '#373737',
                                        'TEXT': '#FFFFFF',
                                        'INPUT': '#474747',
                                        'TEXT_INPUT': '#FFFFFF',
                                        'SCROLL': '#ff00d4',
                                        'BUTTON': ('white', '#474747'),
                                        'PROGRESS': ('#01826B', '#D0D0D0'),
                                        'BORDER': 0, 'SLIDER_DEPTH': 0, 'PROGRESS_DEPTH': 0,
                                        })


sg.theme("CustomDarkTheme")

```

Keep making and publishing!!  GREAT stuff you've done.  And it's highly motivating for me personally to see work like yours.  Really appreciate it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Python 3.6

**Additional context**

Love what you're doing!

**Comment by PETEROLO291** [comment]
Thanks for the support and helpful comments, by now I only code as a hobby since I am only 16.

Allso there are two phrases that I didn't understand:
``You've gone the extra mile by extending PySimpleGUI using the Widget member variable to get to settings not yet exposed``
I don't really understand what are you referring to

``Themes - there's now a call to add a new theme rather than messing with the dictionary directly. I clearly need to update the demos and cookbook.``
And from here I understand absolutely nothing

In addition, I personally think PSG is a very good library, very complete and intuitive,. Love it <3

**Comment by PySimpleGUI** [comment]
> You've gone the extra mile by extending PySimpleGUI using the Widget member variable to get to settings not yet exposed

This is in reference to seeing this code:
```python
# Input details config
window['-I1-'].Widget.configure(highlightcolor='#FFFFFF', highlightbackground="#9C9C9C", insertbackground="White", highlightthickness=1)
window['-I2-'].Widget.configure(highlightcolor='#FFFFFF', highlightbackground="#9C9C9C", insertbackground="White", highlightthickness=1)
```
-----------------------
And this one:

> Themes - there's now a call to add a new theme rather than messing with the dictionary directly. I clearly need to update the demos and cookbook.

was about this code:
```python
sg.LOOK_AND_FEEL_TABLE['CustomDarkTheme'] = {'BACKGROUND': '#373737',
                                        'TEXT': '#FFFFFF',
                                        'INPUT': '#474747',
                                        'TEXT_INPUT': '#FFFFFF',
                                        'SCROLL': '#ff00d4',
                                        'BUTTON': ('white', '#474747'),
                                        'PROGRESS': ('#01826B', '#D0D0D0'),
                                        'BORDER': 0, 'SLIDER_DEPTH': 0, 'PROGRESS_DEPTH': 0,
                                        }

```

Which is now done using:

```python
sg.theme_add_new('CustomDarkTheme', {'BACKGROUND': '#373737',
                                        'TEXT': '#FFFFFF',
                                        'INPUT': '#474747',
                                        'TEXT_INPUT': '#FFFFFF',
                                        'SCROLL': '#ff00d4',
                                        'BUTTON': ('white', '#474747'),
                                        'PROGRESS': ('#01826B', '#D0D0D0'),
                                        'BORDER': 0, 'SLIDER_DEPTH': 0, 'PROGRESS_DEPTH': 0,
                                        })
```

-----------------------------------------

16...  nice.....  I got my first programming job at 16.  I was also washing dishes at Long John Silvers at 16 too (I quit the moment I got a programming job offer)

Keep on building stuff!  It's how you learn programming.

**Comment by PETEROLO291** [comment]
Oh ok thanks!  I will implement that code as soon as I can

Also, I am curious to know, what kind of stuff made you code at age of 16?

**Comment by PySimpleGUI** [comment]
I started coding at 13 when I was first shown a computer.  I instantly knew it was what I am supposed to do.... I don't know what made me think that specific kind of thought as I wasn't religious, but I had a deep feeling somehow that THIS was to be my life.  I took Fortran in college when I was 14 because that's the only place I could use a computer (it was 1978).  I was really driven to learn programming.... loved every moment and still do.

The next year I got an Ohio Scientific computer... not exactly a user friendly computer, but it was something and all we could afford.  I remember the beige color... this model:
![image](https://user-images.githubusercontent.com/46163555/141506243-f7f698f4-acc9-4f35-88de-9a47061e16f3.png)
It had a whopping 4K of RAM and ran Basic or 6502 assembler (that you had to poke into RAM a byte at a time)

Somehow my name made it to the newspaper where the circulation department head had an idea of loaning computers to classrooms as a way to entice kids to become newspaper carriers.  I got the job at $3.35 an hour (the same amount I was making washing dishes), writing small-business games (newspaper route, lemonade stand, etc).  

I couldn't run the code I wrote on my home computer, so I went into their office to use the computer.  They had a TRS-80.  I wrote code in the back of my classes, at school, on paper, and then brought it into the office to type it in and run it.  It was a dream come true kinda job for me back then.

**Comment by PETEROLO291** [comment]
A beautiful story, hope I can live off this in the future.

**Comment by PySimpleGUI** [comment]
Follow your passion.... whatever that may be. 

What part about programming pulled you in?  Why are you learning to code?  What do you want to make?

**Comment by PETEROLO291** [comment]
I started with 14 years making batch files without any knowledge, only knowing how to create loop variables, add delays and print text.  By then, I already knew quite a bit about what could be done with CMD.  I created a couple of batch scripts, and then I felt that urge to create and the freedom that programming gives you to transform an idea into code.  So I followed a 6h tutorial explaining the basics of Python, I don't know why I honestly chose Python.  And I started creating a lot of mini test scripts that I still have.  The only thing that today I don't know how to use are Classes, since I never really understood how I could use them.

**Comment by PySimpleGUI** [comment]
An excellent way you started.

Python was a good choice to start with.  If you're only  training so far is a 6 hour tutorial and building stuff yourself, then you're WAY beyond where many are in your education.

> I felt that urge to create and the freedom that programming gives you to transform an idea into code.

![image](https://user-images.githubusercontent.com/46163555/141649983-16458e3a-84db-4379-9eb1-1b99319529cf.png)

YES!  That's awesome to hear.  An urge to create.  What a gift to have.  Tanay is a young software engineer that works with me and he used a similar word.  He described a need to code.  It sounds like you've got "the gift"... this thing that some people have where programming is innate, natural, doesn't require much effort.  You're fortunate to have discovered yours at an early age!

Don't sweat classes.  PySimpleGUI was the first time I ever wrote a class, and I was programming 40 years up to that point.  The way I tend to use them and think of them is as "a new data type".  If you think about strings, for example, they're a data type that you can do things on like search or change to upper case.  Using a class, you can make another datatype of your own.  There are multiple approaches to using classes and programming in object-oriented style.  One way to get started is to use them in this "new data type" kind of way.

I'm not very good with classes.  Because most of my coding was done with only C, with no classes being a part of the language, I never used them.  With PySimpleGUI, they made sense to me to make the Elements using them.  Button, Text, Input.  They're each sort of a new type, or a new building block.

Give yourself lots of time!  BUILDING THINGS is the way to learn.  You can read about more advanced language features but build your own stuff.  Personally, I don't recommend "tutorials" where you're shown exactly how to do something.

I saw this list of coding projects recently.  It caught my eye because every one of them could use a GUI and they would be easy GUIs to make using PySimpleGUI.

Maybe there's something in there that is of interest....
https://www.codelivly.com/40-python-projects-for-beginners-easy-ideas-to-get-started-coding-python/

Make your own tools!  
I use this kind weird launcher I made

![image](https://user-images.githubusercontent.com/46163555/141650264-18f47225-b358-4570-a00b-544b4a3f6238.png)

It minimizes down to this guy:
![image](https://user-images.githubusercontent.com/46163555/141650270-3de5a43c-ddc5-4c23-a05f-3545f8a09bc5.png)

And I run these "Desktop Widgets" all the time...

![image](https://user-images.githubusercontent.com/46163555/141650318-3e734173-811a-446b-bc8c-9733f3484a70.png)

They're all really handy and optimize my time.   Almost every common thing I do 1-click away.

Even the thing that I get my emoji's from to paste is a PySimpleGUI program.  I press Control Alt Shift F6 and this popups up:

![image](https://user-images.githubusercontent.com/46163555/141650365-02ad2030-b8d5-4386-8ed0-6c849f3fc818.png)

It's fun to finally be able to write stuff for myself.  I've never done a GUI before now.

What is your next project??

**Comment by PETEROLO291** [comment]
> What is your next project??

I'm not sure yet, I'm trying to think something.

First I need to find a need to then code the solving

**Comment by PySimpleGUI** [comment]
> First I need to find a need 

Utilities of some kind maybe?  That's what you've built with your auto-clicker.  

Most of what I make are basically utilities.  In early 2020 I was into trying to draw graphs of covid because no one was running the clock forward.  I ended up with this data visualization thing

![image](https://user-images.githubusercontent.com/46163555/141663380-85c47d3d-5e90-48ff-9ca4-7a640d5590f4.png)

Any kind of graphing thing you want to make or do?

How about downloading information? 

Do AI projects interest you?

I think you're on the right track with being project-focused.  Find the need and fill it.

**Comment by PETEROLO291** [comment]
> Any kind of graphing thing you want to make or do?

Yes, I could implement that in my next project.

> How about downloading information?

Yes, good idea, 90% sure I'll do something like that.

> Do AI projects interest you?

Yes they do, the only thing that I think is something quite complex for me at the moment. Correct me if I'm wrong. And how long would it take to learn the basics of AI?

**Comment by PySimpleGUI** [comment]
Yes for all 3.  Nice!  II like it.

So, here's the deal for something like AI....

If your goal is to make a working program that "does something", with Python, that doesn't mean you have to fully understand that topic.

One of the PySimpleGUI repos is a colorizer.  Another is a YOLO program that labels objects in videos in realtime or in a movie file.  For both of these projects, they were "I want to make a program that does that" projects.  They were not "I want to understand the mathematics behind the YOLO algorithm".  There's a difference between creating and fully understanding absolutely everything about what you're making.

Think about reading and writing files.... you know you can call some Python file I/O to read and write files.  You may have to look up the few lines of code, but you grasp what it's doing.  But, you likely don't know "under the hood", all the way down to the embedded drivers that talk to the disk hardware.  You don't need to know all of the details down to the hardware.  It's fine to stop at the "read and write a file".

This is the same thing with AI or any other technology.  One fun, powerful thing that PySimpleGUI does is to make a friendly interface for a large number of technologies.  You can make a colorizer program like this one without knowing any of the details of HOW these images are colorized:

https://github.com/PySimpleGUI/PySimpleGUI-Photo-Colorizer

![image](https://user-images.githubusercontent.com/46163555/141688677-e4855602-fc0e-4f3b-a15a-1648e41fa58d.png)

In the repo I show exactly where I got the core code:

> ### PyImageSearch
> The code implementing the algorithm is explained in a well-written tutorial by the fine folks at PyImageSearch:
> 
> https://www.pyimagesearch.com/2019/02/25/black-and-white-image-colorization-with-opencv-and-deep-learning/


All of these different kinds of projects.... AI, downloading/scraping, etc, have some core component that you don't have to know how it works, you just need to know how to execute the code.  You need to figure out how to hook up a GUI to it.  Figure that out and you've got yourself a fully working, interesting project.  At **that point**, if you want to dive deeper to understand more about the YOLO AI algorithm, you'll have gotten a start by understanding what it does.

I wrote a Reddit search tool by using the Reddit Praw APIs.  I don't know how they work, but I was able to learn how to connect my code to them.

Come at these project choices from a view of what you would like to have once you're done and then worry about the parts that you'll need to create it.  You'll learn as you go.

Side note..... Today is my 4-year Python anniversary.  I first installed Python 4 years ago today evidently.  It's been a fun trip, and what I am describing above is what I've discovered in those 4 years.  The power of Python is all these little bundles of technology.... what's missing from most of them is a graphical user interface.  Add one of those and you've got yourself a pretty awesome program.

I'm releasing the [psgcompiler](https://pypi.org/project/psgcompiler/) soon, perhaps today.  You'll be able to transform your Python programs into EXE files that you can give to anyone.  

Maybe you would like to make something that you can give a family member or a friend that uses computers, but isn't a programmer?   I've seen these kinds of projects being fun for some people.

Dig down one more level on all those "Yes" answers you gave and see what you find that would be fun to create.

**Comment by PETEROLO291** [comment]
Ok thanks, I'll see what I can do. I'll keep you informed.

Do you use this account as the main one or do you have a personal one?

**Comment by PySimpleGUI** [comment]
This is pretty much it for me.  I have a "Personal" account that I used when I started PySimpleGUI, but I switched over to this one some time back and it's the only one I use.  It's just me, Mike, so there's no one else using it nor will there be in the near future.

I can always be personally reached as well through the mike at PySimpleGUI.org email account.  Or mike at DontBeAMoron.net or any number of other ways ;-)  I'm rarely on Twitter now... the account there is of course "PySimpleGUI".

Please do let me know what you start making!  I find other people's projects really motivating to hear about.
